version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - "/mnt/c/Users/nicko/OneDrive/Pictures/Samsung Gallery/Pictures/to_send/+ reactions imgs:/media"
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9990:80

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
